{% set domainNameNormalized = values.domain | replace("domain:", "") | replace(r/ |_/g, "-") | lower %}
{% set dataProductNameNormalized = values.dataproduct.split(".")[1] | replace(r/ |_/g, "-") | lower %}
{% set componentNameNormalized = values.name | replace(r/ |_/g, "-") | lower %}
{% set dataProductMajorVersion = values.identifier.split(".")[2] %}
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  description: ${{ values.description | dump }}
spec:
  type: storage
  lifecycle: experimental
  owner: ${{ values.developmentGroup }}
  mesh:
    description: ${{ values.description | dump }}
    dependsOn: {% if values.dependsOn | length > 0 %}{% for i in values.dependsOn %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    specific:
      rootFolder: ${{ values.prefixPath }}data-products/${{ domainNameNormalized }}/${{ dataProductNameNormalized }}/${{ dataProductMajorVersion }}
      folder: ${{ componentNameNormalized }}